name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}

        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          rm -rf space_repo
          git clone https://Medina07:$HF_TOKEN@huggingface.co/spaces/Medina07/traffic-signs-cnn space_repo

          rsync -av --exclude='.git' ./hf_space/ space_repo/

          cd space_repo
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "No changes"
          git push